<%@ Page Language="C#" EnableEventValidation="false" AutoEventWireup="true" CodeBehind="Login.aspx.cs" Inherits="AngularJS_Login.Login" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>
        td
        {
           margin:10px;
            background-color:antiquewhite;
            border-color:brown;
           
        } 
        .margin
        {
            margin:20px;
        }
    </style>
    <script src="Scripts/angular.js"></script>
    <script src="Scripts/bootstrap.js"></script>
    <script src="Scripts/jquery-3.1.0.js"></script>
    <script src="Scripts/angular.min.js"></script>
    <script src="Scripts/jquery-3.1.0.min.js"></script>
    <script src="Scripts/bootstrap.min.js"></script>
    <link href="CSS/bootstrap.min.css" rel="stylesheet"/>

    
    <script>
        var mymodal = angular.module('mymodal', []);

        mymodal.controller('MainCtrl', function ($scope) {
            $scope.showModal = false;
            $scope.toggleModal = function(){
                $scope.showModal = !$scope.showModal;
            };
        });

        mymodal.directive('modal', function () {
            return {
                template: '<div class="modal fade">' + 
                    '<div class="modal-dialog">' + 
                      '<div class="modal-content">' + 
                        '<div class="modal-header">' + 
                          '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' + 
                          '<h4 class="modal-title">{{ title }}</h4>' + 
                        '</div>' + 
                        '<div class="modal-body" ng-transclude></div>' + 
                      '</div>' + 
                    '</div>' + 
                  '</div>',
                restrict: 'E',
                transclude: true,
                replace:true,
                scope:true,
                link: function postLink(scope, element, attrs) {
                    scope.title = attrs.title;

                    scope.$watch(attrs.visible, function(value){
                        if(value == true)
                            $(element).modal('show');
                        else
                            $(element).modal('hide');
                    });

                    $(element).on('shown.bs.modal', function(){
                        scope.$apply(function(){
                            scope.$parent[attrs.visible] = true;
                        });
                    });

                    $(element).on('hidden.bs.modal', function(){
                        scope.$apply(function(){
                            scope.$parent[attrs.visible] = false;
                        });
                    });
                }
            };
        });
    </script>


</head>
<body ng-app="mymodal">
    <form id="form1" runat="server">
            <div ng-controller="MainCtrl" class="container">
                <h1>Modal example</h1>
                <input type="text" class="btn btn-default" value="Open" ng-click="toggleModal()"/>
                <asp:Button runat="server" CssClass="btn btn-default" OnClick="List_Click" Text="List Data"></asp:Button>
                <modal title="Login form" visible="showModal">
                    <form role="form">
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <asp:TextBox runat="server" ID="email" placeholder="Enter email" CssClass="form-control"></asp:TextBox>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <asp:TextBox runat="server" ID="pass" placeholder="Enter email" CssClass="form-control"></asp:TextBox>
                        </div>
                        <!-- USE HERE ANGULAR ROUGHTING CONCEPT -->
                        <asp:Button runat="server" CssClass="btn btn-default" OnClick="Unnamed1_Click" Text="Submit"></asp:Button>
                        <asp:Button runat="server" CssClass="btn btn-default" OnClick="Register_Click" Text="Register"></asp:Button>
                    </form>
                </modal>
                <br/><br/><br/><br/>
                <table>
                <tr>
                    <td>
                        <asp:GridView ID="gv1" runat="server" DataKeyNames="id" OnRowEditing="gv1_RowEditing" OnRowUpdating="gv1_RowUpdating" OnRowDeleting="gv1_RowDeleting" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateColumns="false" >
                        <Columns>
                        <asp:TemplateField HeaderText="Email">
                        <EditItemTemplate>
                            <asp:TextBox CssClass="margin" ID="t1" runat="server" Text='<%# Eval("email") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label CssClass="margin" ID="l1"  runat="server" Text='<%# Eval("email") %>'></asp:Label>
                        </ItemTemplate>
                        </asp:TemplateField>
                        </Columns>
                        <Columns>
                        <asp:TemplateField HeaderText="Password">
                        <EditItemTemplate>
                            <asp:TextBox CssClass="margin" ID="t2"  runat="server" Text='<%# Eval("password") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label CssClass="margin" ID="l2"  runat="server" Text='<%# Eval("password") %>'></asp:Label>
                        </ItemTemplate>
                        </asp:TemplateField>
                        </Columns>
                        <Columns>
                        <asp:TemplateField HeaderText="Id">
                        <ItemTemplate>
                            <asp:Label CssClass="margin" ID="l3"  runat="server" Text='<%# Eval("id") %>'></asp:Label>
                        </ItemTemplate>
                        </asp:TemplateField>
                        </Columns>
                        </asp:GridView>
                    </td>
                </tr>
                </table>
            </div>
    </form>
</body>
</html>
